# .graphclientrc.yml
sources:
  - name: safetyfirst
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/4851/saferyfirst/v0.0.8
  
documents:
  - ./utils/graphql/disaster.graphql
